const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const { authenticateToken } = require('../middleware/auth');
const Report = require('../models/Report');

// Get all reports for logged-in user
router.get('/', authenticateToken, async (req, res) => {
  try {
    const reports = await Report.find({ user_id: req.user.user_id })
      .sort({ timestamp: -1 })
      .select('-__v');
    
    res.json({ success: true, reports });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Get single report
router.get('/:report_id', authenticateToken, async (req, res) => {
  try {
    const report = await Report.findOne({ 
      report_id: req.params.report_id,
      user_id: req.user.user_id 
    }).select('-__v');
    
    if (!report) {
      return res.status(404).json({ error: 'Report not found' });
    }
    
    res.json({ success: true, report });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Download PDF report
router.get('/:report_id/download', authenticateToken, async (req, res) => {
  try {
    const report = await Report.findOne({ 
      report_id: req.params.report_id,
      user_id: req.user.user_id 
    });
    
    if (!report) {
      return res.status(404).json({ error: 'Report not found' });
    }
    
    // Create PDF
    const doc = new PDFDocument({ margin: 50 });
    const filename = `cattle-report-${report.report_id}.pdf`;
    
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    
    doc.pipe(res);
    
    // Header
    doc.fontSize(24).fillColor('#2563eb').text('Cattle Health Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(10).fillColor('#666').text(`Report ID: ${report.report_id}`, { align: 'center' });
    doc.text(`Generated: ${new Date(report.timestamp).toLocaleString()}`, { align: 'center' });
    doc.moveDown(2);
    
    // User Information
    doc.fontSize(14).fillColor('#000').text('Farmer Information', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11).text(`Name: ${report.user_name}`);
    doc.text(`User ID: ${report.user_id}`);
    doc.moveDown(1.5);
    
    // Diagnosis Results
    doc.fontSize(14).text('Diagnosis Results', { underline: true });
    doc.moveDown(0.5);
    
    const statusColor = report.status === 'Healthy' ? '#10b981' : '#ef4444';
    doc.fontSize(12).fillColor(statusColor).text(`Status: ${report.status}`, { bold: true });
    doc.fillColor('#000');
    
    if (report.status === 'Diseased') {
      doc.text(`Disease: ${report.disease_name}`);
      doc.text(`Stage: ${report.stage}`);
    }
    
    doc.text(`Confidence: ${report.confidence}%`);
    doc.moveDown(1.5);
    
    // Precautions
    doc.fontSize(14).text('Recommended Precautions', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11);
    
    report.precautions.forEach((precaution, index) => {
      doc.text(`${index + 1}. ${precaution}`, { indent: 20 });
      doc.moveDown(0.3);
    });
    
    // Footer
    doc.moveDown(3);
    doc.fontSize(9).fillColor('#666').text(
      '⚠️ This report is generated by an AI system. Please consult a qualified veterinarian for professional diagnosis and treatment.',
      { align: 'center', width: 500 }
    );
    
    doc.end();
  } catch (error) {
    console.error('PDF Generation Error:', error);
    res.status(500).json({ error: error.message });
  }
});

module.exports = router;